[book]
authors = ["Arthur Paulino, Damiano Testa, Edward Ayers, Evgenia Karunus, Henrik BÃ¶ving, Jannis Limperg, Siddhartha Gadgil, Siddharth Bhat"]
language = "en"
multilingual = false
src = "md"
title = "Metaprogramming in Lean 4"

[output.html]
git-repository-url = "https://github.com/leanprover-community/lean4-metaprogramming-book"
additional-css = ["./assets/pagetoc.css"]
additional-js = [
  "assets/blockPlay.js",
  "assets/pagetoc.js"
]